timezone: America/Los_Angeles

# GitHub Flavored Markdown
markdown: GFM

exclude:
  - CNAME
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - scripts
  - static
  - yarn.lock

defaults:
  - scope:
      path: ./public/buns.json
    values:
      permalink: /v1/buns
