name: Publish to GitHub Pages

on:
  # auto-run when pushed to the default branch
  # push:
  #   branches: [$default-branch]

  # manually run from GitHub Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout master
        uses: actions/checkout@v4
      - id: root-index
        name: Merge README.md w/ public index.md
        run: |-
          cat ./README.md | perl -ne 's/\.github\///; print;' >> ./public/index.md
          cp -v ./.github/showdex-lib.png ./public
      - id: setup
        name: Configure pages
        uses: actions/configure-pages@v5
      - id: build
        name: Jelq public to dist
        uses: actions/jekyll-build-pages@v1
        with: # `destination` must match `path` input of actions/upload-pages-artifact
          source: ./public
          destination: ./dist
      - id: upload
        name: Upload dist artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
